### ISSUE TITLE
Configuration folder is often not the same as data folder

### ISSUE THREAD

**Issue by frinux** [samdoran/ansible-role-pgsql-replication#11]
https://github.com/samdoran/ansible-role-pgsql-replication/blob/ae7bc9bd6ebfbdc32925e53fae36b7a5e522130f/tasks/master.yml#L5

I think pgsqlrep_data_path should not be used for this.

I tried to understand where this configuration folder comes from. I'm not familiar with molecule, but it seems there is a problem with your repository. There is a weird folder containing (old ?) config: ./molecule/default/postgres/vars/Ubuntu.yml for instance.

pg_conf_dir seems to be declared but not used, is it referring to an old version (which shouldn't have been committed?)

Thanks

**Comment by samdoran** [comment]
> I think pgsqlrep_data_path should not be used for this.

I'm confused. What should be used? The path to the configuration file is `/var/lib/pgsql/{{ pgsql_version }}/data/postgresql.conf`.

> I tried to understand where this configuration folder comes from.

It's created when PostgreSQL is installed.

>  I'm not familiar with molecule, but it seems there is a problem with your repository. There is a weird folder containing (old ?) config: ./molecule/default/postgres/vars/Ubuntu.yml for instance.

Everything inside the `molecule` directory is strictly for testing. Those are roles I'm reusing from somewhere else for tests. I didn't look at them too closely since I only need them for testing.

The `Ubuntu.yml` file will be picked up on Ubuntu systems by [this task](https://github.com/samdoran/ansible-role-pgsql-replication/blob/80f53663dc0b8ad909dc4610116f37cdb6e438e2/molecule/default/postgres/tasks/vars.yml#L3).
